#!/usr/bin/bash

set -o nounset
set -o pipefail
set -o errexit

readonly OS=linux

/usr/bin/curl --silent\
  https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
  /usr/bin/grep browser_download |\
  /usr/bin/grep "$OS" |\
  /usr/bin/cut --delimiter='"' --field=4 |\
  /usr/bin/xargs /usr/bin/curl --location --remote-name

/usr/bin/mv kustomize_kustomize\.v*_${OS}_amd64 /usr/local/bin/kustomize
/usr/bin/chmod a+x /usr/local/bin/kustomize
