#!/usr/bin/bash

set -o nounset
set -o pipefail
set -o errexit

readonly OS=linux

/usr/bin/curl --silent\
  https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
  /usr/bin/grep browser_download |\
  /usr/bin/grep "$OS" |\
  /usr/bin/cut --delimiter='"' --field=4 |\
  /usr/bin/grep /kustomize/v |\
  /usr/bin/sort |\
  /usr/bin/tail -n 1 |\
  /usr/bin/xargs /usr/bin/curl --location --remote-name

/usr/bin/tar xzf kustomize_v*_${OS}_amd64.tar.gz
/usr/bin/mv kustomize /usr/local/bin/kustomize
/usr/bin/rm kustomize_v*_${OS}_amd64.tar.gz
