#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

readonly os=linux

curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
  grep browser_download |\
  grep "$os" |\
  cut -d '"' -f 4 |\
  grep /kustomize/v |\
  sort |\
  tail -n 1 |\
  xargs curl -LO

tar -xzf kustomize_v*_${os}_amd64.tar.gz
mv kustomize /usr/local/bin/kustomize
rm kustomize_v*_${os}_amd64.tar.gz
