#!/usr/bin/bash

set -o nounset
set -o errexit

readonly REPO="shellbro/cicd-k8s-tools"
readonly TAG=$(cat VERSION)

/usr/bin/docker pull "$REPO"
/usr/bin/docker tag "$REPO" "$REPO:$TAG"
/usr/bin/docker push "$REPO:$TAG"
